Day/feat/cover absence
UXIT-Contractors/UXIT-Planner-App pull request #48
Opened 2023-06-19 09:49 UTC by daymeijroos

### Title: 
Feature: Cover Absence Functionality

### Description:
This pull request introduces the "Cover Absence" functionality into the UXIT-Planner-App. This feature allows team members to cover the shifts of their colleagues who are absent, providing better flexibility and cooperation within the team. 

Key changes include:

- The introduction of new models: EvenWeek, OddWeek, and ReservationWeek to schema.prisma.
- Improvements to backup generation, with the system now generating two backups per day.
- The creation of an "Absence" page, which provides a user interface for managing absences.
- The implementation of the "cover a shift" feature, which allows users to volunteer to cover the shifts of absent colleagues.

### Testing:

To test these changes, follow these steps:

1. Pull the changes from the `day/feat/cover-absence` branch.
2. Make sure to build the project and update the database schema with the new models, and log out and in again after.
3. Visit the new "open-shift/birthday" page and familiarize yourself with its interface. (this page works like [open-shift/[id] but i included the birthday to be able to test)
4. Test the "Neem shift" functionality by clicking the button, the open-shift should be gone from the database and appeared in your schedule on the right day.

### Request:

Please review the changes, test the new functionalities as described above, and if everything is satisfactory, merge this branch into the master branch.

2023-06-19 23:01 UTC, Sjors-Hoogenboom commented
![image](https://github.com/UXIT-Contractors/UXIT-Planner-App/assets/79990968/13c39401-1222-438f-a3d3-fa5ea33dcd11)
Voordat ik naar de code ga kijken heb ik npm run build gedaan (na de seed en install)
Maar er zit nog any errors 💀 Dus ik kan hem al niet approven

2023-06-19 23:11 UTC, Sjors-Hoogenboom commented on prisma/seed.ts
> +  // const mockUser1 = await prisma.user.create({
Me confused, why comment?

2023-06-19 23:17 UTC, Sjors-Hoogenboom commented on server/api/schedule/checks.ts
> +export const checkUserFlexibleAvailability = (user: UserWithPreferenceAndStaffings, on: Date): boolean => {
What is on in on: Date?  Kind of weird name ngl

2023-06-19 23:20 UTC, Sjors-Hoogenboom commented on server/api/schedule/checks.ts
> +  if (!(user.preference && user.preference.availability_flexible)) return false
instead of: if (!(user.preference && user.preference.availability_flexible))
use if (!user.preference && !user.preference.availability_flexible) 

(idk that's what I prefer)

2023-06-19 23:26 UTC, Sjors-Hoogenboom commented on server/api/schedule/generate-functions.ts
> +  const amountBackupNeeded = 2 //💀
💀

2023-06-19 23:26 UTC, Sjors-Hoogenboom commented on server/api/schedule/generate-functions.ts
> +  for (let index = 0; index < amountBackupNeeded; index++) {
Ik ben het nog steeds niet eens met i vervangen naar index

2023-06-19 23:36 UTC, Sjors-Hoogenboom commented on server/api/schedule/generate-functions.ts
> +  for (var index = array.length - 1; index > 0; index--) {
Ik ben het nog steeds niet eens met i vervangen naar index bij de code review
Maar de j is wel beter nu

2023-06-19 23:37 UTC, Sjors-Hoogenboom commented on server/types/availibility.ts
> -export interface AvailabilityWeekWithAvailibilityWithShiftTypes extends AvailabilityWeek {
Thank god AvailabilityWeekWithAvailibilityWithShiftTypes is gone

2023-06-19 23:45 UTC, Sjors-Hoogenboom commented on src/components/elements/schedule/team-staffing-list.tsx
> +    uniqueStaffings = staffings.data.reduce((accumulator: StaffingWithColleagues[], current: StaffingWithColleagues) => {
Gives ESLint any type 💀

2023-06-19 23:49 UTC, Sjors-Hoogenboom requested changes
Any types need fixing, not really much feedback besides that

2023-06-19 23:50 UTC, Sjors-Hoogenboom commented
Feature does work as intended though

2023-06-20 08:05 UTC, daymeijroos commented on server/api/schedule/checks.ts
> +  if (!(user.preference && user.preference.availability_flexible)) return false
That wont work, because if !user.preference then preference is undefined and we cant test if availability exists, compiler will shit itself

2023-06-20 08:16 UTC, daymeijroos commented on server/api/schedule/checks.ts
> +export const checkUserFlexibleAvailability = (user: UserWithPreferenceAndStaffings, on: Date): boolean => {
Fixed

2023-06-20 08:17 UTC, daymeijroos commented on server/api/schedule/generate-functions.ts
> +  const amountBackupNeeded = 2 //💀
💀

2023-06-20 08:21 UTC, daymeijroos commented on src/components/elements/schedule/team-staffing-list.tsx
> +    uniqueStaffings = staffings.data.reduce((accumulator: StaffingWithColleagues[], current: StaffingWithColleagues) => {
It doesnt, thats webstorm, but i fixed it
<img width="520" alt="image" src="https://github.com/UXIT-Contractors/UXIT-Planner-App/assets/78052708/03df937a-05f1-4492-9144-d42c6570452c">

definitely better💀💀

2023-06-20 12:45 UTC, Sjors-Hoogenboom approved these changes
![luigispin](https://github.com/UXIT-Contractors/UXIT-Planner-App/assets/79990968/8b8a1ba3-3c3a-4ac4-8e3e-08b0f3bfa262)
Changes look good
I approve

2023-06-20 12:45 UTC, merged